########
# NOP-1
########
[experiment.nop1_pass_arm32_pass]
command = "x_nop"
program-file = "test_files/password_check.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/nop1_arm32_password_check"
yes= true
target = "arm_32"
num_cpus=24
num_nops=1


########
# NOP-2
########
[experiment.nop2_pass_arm32_pass]
command = "x_nop"
program-file = "test_files/password_check.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/nop2_arm32_password_check"
yes= true
target = "arm_32"
num_cpus=24
num_nops=2

########
# NOP-4
########
[experiment.nop4_pass_arm32_pass]
command = "x_nop"
program-file = "test_files/password_check.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/nop4_arm32_password_check"
yes= true
target = "arm_32"
num_cpus=24
num_nops=4

########
# NOP-8
########
[experiment.nop8_pass_arm32_pass]
command = "x_nop"
program-file = "test_files/password_check.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/nop8_arm32_password_check"
yes= true
target = "arm_32"
num_cpus=24
num_nops=8

