####################
# 4-NOP 
####################

[experiment.nop4_arm32_opt0_fib]
command = "x_nop"
program-file = "test_files/fib.c"
program-input = ""
expected-returncode = 0 
expected-stdout = "6765"
list-expected = false 
timeout = 4 
out-dir = "experiments/nop4_arm32_opt0_fib"
yes= true
target = "arm_32"
num_cpus=24
num_nops=4



[experiment.nop4_arm32_opt0_fib_loopcheck]
command = "x_nop"
program-file = "test_files/fib_LOOPCHECK.c"
program-input = ""
expected-returncode = 0 
expected-stdout = "6765"
list-expected = false 
timeout = 4 
out-dir = "experiments/nop4_arm32_opt0_fib_LOOPCHECK"
yes= true
target = "arm_32"
num_cpus=24
num_nops=4

########
# 1-NOP
########
[experiment.nop1_arm32_opt0_fib]
command = "x_nop"
program-file = "test_files/fib.c"
program-input = ""
expected-returncode = 0 
expected-stdout = "6765"
list-expected = false 
timeout = 4 
out-dir = "experiments/nop1_arm32_opt0_fib"
yes= true
target = "arm_32"
num_cpus=24



[experiment.nop1_arm32_opt0_fib_loopcheck]
command = "x_nop"
program-file = "test_files/fib_LOOPCHECK.c"
program-input = ""
expected-returncode = 0 
expected-stdout = "6765"
list-expected = false 
timeout = 4 
out-dir = "experiments/nop1_arm32_opt0_fib_LOOPCHECK"
yes= true
target = "arm_32"
num_cpus=24



########
# NOP-8
########

[experiment.nop8_arm32_opt0_fib]
command = "x_nop"
program-file = "test_files/fib.c"
program-input = ""
expected-returncode = 0 
expected-stdout = "6765"
list-expected = false 
timeout = 4 
out-dir = "experiments/nop8_arm32_opt0_fib"
yes= true
target = "arm_32"
num_cpus=24
num_nops=8



[experiment.nop8_arm32_opt0_fib_loopcheck]
command = "x_nop"
program-file = "test_files/fib_LOOPCHECK.c"
program-input = ""
expected-returncode = 0 
expected-stdout = "6765"
list-expected = false 
timeout = 4 
out-dir = "experiments/nop8_arm32_opt0_fib_LOOPCHECK"
yes= true
target = "arm_32"
num_cpus=24
num_nops=8


########
# 2-NOP
########

[experiment.nop_arm32_opt0_fib]
command = "x_nop"
program-file = "test_files/fib.c"
program-input = ""
expected-returncode = 0 
expected-stdout = "6765"
list-expected = false 
timeout = 4 
out-dir = "experiments/nop2_arm32_opt0_fib"
yes= true
target = "arm_32"
num_cpus=24
num_nops=2



[experiment.nop_arm32_opt0_fib_loopcheck]
command = "x_nop"
program-file = "test_files/fib_LOOPCHECK.c"
program-input = ""
expected-returncode = 0 
expected-stdout = "6765"
list-expected = false 
timeout = 4 
out-dir = "experiments/nop2_arm32_opt0_fib_LOOPCHECK"
yes= true
target = "arm_32"
num_cpus=24
num_nops=2



