
[experiment.nop_arm32]
command = "x-nop"
program-file = "test_files/password_check.c"
program-input = "Incorrect\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 2
out-dir = "experiments/nop_arm32_password_check"
yes= true
target = "arm_32"
num_cpus=24
