
[experiment.para_bit_arm32]
command = "para_bit"
program-file = "test_files/password_check.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_bit_arm32_password_check"
yes= true
target = "arm_32"
num_cpus=8
save-results="experiments/para_bit_arm32_password_check/result.csv"


