
[experiment.nop_arm64]
command = "nop"
program-file = "test_files/password_check.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/nop_arm64_password_check"
yes= true
target = "arm_64"
num_cpus=8
