[experiment.para_nop_AVR]
command = "para_nop"
program-file = "test_files/avr_password.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 0.5 
out-dir = "experiments/para_nop_avr_password_check"
yes= true
target = "AVR"
num_cpus=8

