

########
# NOP
########

[experiment.para_nop_pass_ricv64]
command = "para_nop"
program-file = "test_files/password_check.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_nop_ricv64_password_check"
yes= true
target = "riscv"
num_cpus=8

[experiment.para_nop_ricv64_pass_detect]
command = "para_nop"
program-file = "test_files/password_check_DETECT.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_nop_ricv64_password_check_DETECT"
yes= true
target = "riscv"
num_cpus=8


[experiment.para_nop_ricv64_pass_branch]
command = "para_nop"
program-file = "test_files/password_check_BRANCH.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_nop_ricv64_password_check_BRANCH"
yes= true
target = "riscv"
num_cpus=8


[experiment.para_nop_ricv64_pass_double_check]
command = "para_nop"
program-file = "test_files/password_check_DOUBLE_CHECK.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_nop_ricv64_password_check_DOUBLE_CHECK"
yes= true
target = "riscv"
num_cpus=8


[experiment.para_nop_ricv64_fib]
command = "para_nop"
program-file = "test_files/fib.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_nop_ricv64_fib"
yes= true
target = "riscv"
num_cpus=8



[experiment.para_nop_ricv64_fib]
command = "para_nop"
program-file = "test_files/fib_LOOPCHECK.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_nop_ricv64_fib_LOOPCHECK"
yes= true
target = "riscv"
num_cpus=8



########
# BIT
########

[experiment.para_bit_pass_ricv64]
command = "para_bit"
program-file = "test_files/password_check.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_bit_ricv64_password_check"
yes= true
target = "riscv"
num_cpus=8

[experiment.para_bit_ricv64_pass_detect]
command = "para_bit"
program-file = "test_files/password_check_DETECT.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_bit_ricv64_password_check_DETECT"
yes= true
target = "riscv"
num_cpus=8


[experiment.para_bit_ricv64_pass_branch]
command = "para_bit"
program-file = "test_files/password_check_BRANCH.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_bit_ricv64_password_check_BRANCH"
yes= true
target = "riscv"
num_cpus=8


[experiment.para_bit_ricv64_pass_double_check]
command = "para_bit"
program-file = "test_files/password_check_DOUBLE_CHECK.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_bit_ricv64_password_check_DOUBLE_CHECK"
yes= true
target = "riscv"
num_cpus=8


[experiment.para_bit_ricv64_fib]
command = "para_bit"
program-file = "test_files/fib.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_bit_ricv64_fib"
yes= true
target = "riscv"
num_cpus=8



[experiment.para_bit_ricv64_fib]
command = "para_bit"
program-file = "test_files/fib_LOOPCHECK.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_bit_ricv64_fib_LOOPCHECK"
yes= true
target = "riscv"
num_cpus=8


