
######################################################################
# Password check experiment
######################################################################

[experiment.para_nop_x86]
command = "para_nop"
program-file = "test_files/password_check.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_nop_x86_64_password_check"
yes= true
target = "x86_64"
num_cpus=8

[experiment.para_bit_x86]
command = "para_bit"
program-file = "test_files/password_check.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_bit_x86_64_password_check"
yes= true
target = "x86_64"
num_cpus=8


[experiment.para_nop_riscv]
command = "para_nop"
program-file = "test_files/password_check.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_nop_riscv_password_check"
yes= true
target = "riscv"
num_cpus=8

[experiment.para_bit_riscv]
command = "para_bit"
program-file = "test_files/password_check.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_bit_riscv_password_check"
yes= true
target = "riscv"
num_cpus=8


[experiment.para_nop_arm32]
command = "para_nop"
program-file = "test_files/password_check.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_nop_arm32_password_check"
yes= true
target = "arm_32"
num_cpus=8

[experiment.para_bit_arm64]
command = "para_bit"
program-file = "test_files/password_check.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_bit_arm64_password_check"
yes= true
target = "arm64"
num_cpus=8



######################################################################
# fib experiment
######################################################################
[experiment.para_nop_x86]
command = "para_nop"
program-file = "test_files/fib.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_nop_x86_64_fib"
yes= true
target = "x86_64"
num_cpus=8

[experiment.para_bit_x86]
command = "para_bit"
program-file = "test_files/fib.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_bit_x86_64_fib"
yes= true
target = "x86_64"
num_cpus=8


[experiment.para_nop_riscv]
command = "para_nop"
program-file = "test_files/fib.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_nop_riscv_fib"
yes= true
target = "riscv"
num_cpus=8

[experiment.para_bit_riscv]
command = "para_bit"
program-file = "test_files/fib.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_bit_riscv_fib"
yes= true
target = "riscv"
num_cpus=8


[experiment.para_nop_arm32]
command = "para_nop"
program-file = "test_files/fib.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_nop_arm32_fib"
yes= true
target = "arm_32"
num_cpus=8

[experiment.para_bit_arm64]
command = "para_bit"
program-file = "test_files/fib.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_bit_arm64_fib"
yes= true
target = "arm64"
num_cpus=8




######################################################################
# fib_loop_check.c experiment
######################################################################
[experiment.para_nop_x86]
command = "para_nop"
program-file = "test_files/fib_loop_check.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_nop_x86_64_fib_loop_check"
yes= true
target = "x86_64"
num_cpus=8

[experiment.para_bit_x86]
command = "para_bit"
program-file = "test_files/fib_loop_check.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_bit_x86_64_fib_loop_check"
yes= true
target = "x86_64"
num_cpus=8


[experiment.para_nop_riscv]
command = "para_nop"
program-file = "test_files/fib_loop_check.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_nop_riscv_fib_loop_check"
yes= true
target = "riscv"
num_cpus=8

[experiment.para_bit_riscv]
command = "para_bit"
program-file = "test_files/fib_loop_check.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_bit_riscv_fib_loop_check"
yes= true
target = "riscv"
num_cpus=8


[experiment.para_nop_arm32]
command = "para_nop"
program-file = "test_files/fib_loop_check.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_nop_arm32_fib_loop_check"
yes= true
target = "arm_32"
num_cpus=8

[experiment.para_bit_arm64]
command = "para_bit"
program-file = "test_files/fib_loop_check.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_bit_arm64_fib_loop_check"
yes= true
target = "arm64"
num_cpus=8




