
[experiment.nop_arm32]
command = "x_nop"
program-file = "test_files/password_check.c"
program-input = "Incorrect\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 2 
out-dir = "experiments/1nop_arm32_opt0_password_check"
yes= true
target = "arm_32"
num_cpus=24


[experiment.nop_arm64]
command = "x_nop"
program-file = "test_files/password_check.c"
program-input = "Incorrect\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 2 
out-dir = "experiments/1nop_arm64_opt0_password_check"
yes= true
target = "arm_64"
num_cpus=24


[experiment.nop_x86]
command = "x_nop"
program-file = "test_files/password_check.c"
program-input = "Incorrect\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 2 
out-dir = "experiments/1nop_x86_64_opt0_password_check"
yes= true
target = "x86_64"
num_cpus=24


[experiment.nop_x86_32]
command = "x_nop"
program-file = "test_files/password_check.c"
program-input = "Incorrect\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 2 
out-dir = "experiments/1nop_x86_32_opt0_password_check"
yes= true
target = "x86_32"
num_cpus=24


