
[experiment.para_nop_x86_64]
command = "para_nop"
program-file = "test_files/password_check.c"
program-input = "wrong\n"
expected-returncode = 0 
expected-stdout = "Correct"
list-expected = false 
timeout = 4 
out-dir = "experiments/para_nop_x86_64_password_check"
yes= true
target = "x86_64"
num_cpus=8

