[password_check]
context = "Program that uses a simple boolean, a detect checksum, and single conditional to check for a correct password"
vulnerablities =[ "4.6) Double Check", "4.8) Branch"]
mitigations= [ "4.3) Detect"]
