[experiment.nop1_password_check_branch]
#context = "Program that uses a complex flag and single conditional to check for a correct password"
#vulnerablities = ["4.3) Detect", "4.6) Double Check"]
#mitigations = ["4.8) Branch"]
command = "x_nop"
program-file = "test_files/password_check/experiment_files/password_check_BRANCH.c"
out_dir = "test_files/password_check/output/branch/nop-1"
program-input = "Incorrect"
expected-returncode = 0
expected-stdout = "Correct"
timeout = 1
target = "ARM_32"
num_cpus = 2
yes = true
upset_on_match = true
num_nops = 1
