[password_check]
context = "Program that uses a complex flag and single conditional to check for a correct password"
vulnerablities =["4.3) Detect", "4.6) Double Check" ]
mitigations= ["4.8) Branch" ]
