[experiment.nop1_unmasked-aes-new-iv-encrypt]
command = "x_nop"
program-file = "test_files/Unmasked_AES/Experiment_Files/unmasked-new-iv.c"
out_dir = "test_files/Unmasked_AES/Output/new-iv/aes128-cbc-encrypt-nop-1"
program-input = ""
expected-returncode = 0
expected-stdout = "0b483b1c2cada6e07e6edab1bd06cd15332c4c48594444b5106b701938aed8050981cd24430beb0917f40789ed9ce8509fa938defa0cdade822fb95176e93128"
timeout = 1
target = "ARM_32"
num_cpus = 2
yes = true
upset_on_match = false
num_nops = 1
opts = "-DAES128 -DCBC=1 -DENCRYPT"

[experiment.nop1_unmasked-aes-new-iv-decrypt]
command = "x_nop"
program-file = "test_files/Unmasked_AES/Experiment_Files/unmasked-new-iv.c"
out_dir = "test_files/Unmasked_AES/Output/new-iv/aes128-cbc-decrypt-nop-1"
program-input = ""
expected-returncode = 0
expected-stdout = "6bc1bee22e409f96e93d7e117393172aae2d8a571e03ac9c9eb76fac45af8e5130c81c46a35ce411e5fbc1191a0a52eff69f2445df4f9b17ad2b417be66c3710"
timeout = 1
target = "ARM_32"
num_cpus = 2
yes = true
upset_on_match = false
num_nops = 1
opts = "-DAES128 -DCBC=1 -DDECRYPT"
