[experiment.nop1_masked-aes-new-key-encrypt]
command = "x_nop"
program-file = "test_files/Masked_AES/Experiment_Files/masked-new-key.c"
out_dir = "test_files/Masked_AES/Output/new-key/aes128-cbc-encrypt-nop-1"
program-input = ""
expected-returncode = 0
expected-stdout = "cd8a8657ae85577d53de6af0462613f83aaef4e2f6960cfbf0b67edc6c585f415bf3862c1ed7721bc64c8c553468a5a4a4167129f85cbe283d5bf9211ab3098b"
timeout = 1
target = "ARM_32"
num_cpus = 2
yes = true
upset_on_match = false
num_nops = 1
opts = "-DAES128 -DCBC=1 -DENCRYPT"

[experiment.nop1_masked-aes-new-key-decrypt]
command = "x_nop"
program-file = "test_files/Masked_AES/Experiment_Files/masked-new-key.c"
out_dir = "test_files/Masked_AES/Output/new-key/aes128-cbc-decrypt-nop-1"
program-input = ""
expected-returncode = 0
expected-stdout = "6bc1bee22e409f96e93d7e117393172aae2d8a571e03ac9c9eb76fac45af8e5130c81c46a35ce411e5fbc1191a0a52eff69f2445df4f9b17ad2b417be66c3710"
timeout = 1
target = "ARM_32"
num_cpus = 2
yes = true
upset_on_match = false
num_nops = 1
opts = "-DAES128 -DCBC=1 -DDECRYPT"
